algoritmo "exerc3"
//declaraçao das variaveis
var
X,Y, soma, subtracao, multiplicacao: inteiro
//entrada de dados
inicio
escreval ("Digite dois números inteiros: ")
leia (X)
leia (Y)
//processamento
soma <- X+Y
subtracao <- X-Y
multiplicacao <- X*Y
escreval
//saida de dados
escreval ("SOMA: ", soma)
escreval ("SUBTRAÇÃO: ", subtracao)
escreval ("MULTIPLICAÇÃO: ", multiplicacao)
escreval ()





fimalgoritmo